### ISSUE TITLE
주제 구체화하기

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#1]
저번 짧은 발표 시간에 받은 피드백 및 추가로 해당 주제 기획과 관련된 아이디어 있으시면  word문서에 작성해 주시면 됩니다. 
작성 이후 commit 하실 때, commit message 바닥글에 이번 이슈 번호 작성하시면 됩니다.

**Comment by kimnamhyeon0112** [comment]
부가기능
만약 부득이한 이유로 거래 불가할 시 대체품목 추천, 해당품목 지도에 표시

**Comment by poeo1877** [comment]
대체 품목 추천 기준은 어떻게 하실 건가요?

**Comment by kimnamhyeon0112** [comment]
예를들어 우리가 음식을 만든다고 가정할 때 물엿이 전세계적으로 대란이라 구할 수 없을때 꿀이라는 대체품목을 추천하는 것입니다.

**Comment by poeo1877** [comment]
대체재 뿐 만 아니라 보완재도 알려주는 방식은 어떤가요?
아마 이렇게 되면 원자재만 알리는 지도가 아니라, 산업 전반적인 주요 상품을 다루는 프로그램으로 될 것 같습니다

**Comment by kimnamhyeon0112** [comment]
좋은 생각인 것 같습니다. 자료의 다양성은 더욱 완성도 높은 결과물을 도출할 수 있으니까요. 
하지만 아시다시피 남용은 금해야 할것입니다. 오히려 완성도를 떨어뜨릴수도 있구요.
