### ISSUE TITLE
추천검색어에 관한 궁금증

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#10]
현재 추천검색어 코드를 짜는 중입니다. 구글링하던중 javascript의 fetch로 리소스를 비동기 요청하는 방식을 찾았습니다.
 이 방식은 API를 호출하고 URL에서 응답 데이터를 받아오는 방식입니다.
 const getData = async () => {
    const response = await fetch("https://reqres.in/api/users?page=1")
    return response.json()
}
이런형식으로 선언되며 링크에 저장되어있는 글자가 index.html의 검색창에서 검색을 하면 추천검색어로 뜨는 방식입니다.
위에 올려드린 링크대로라면 Geroge Bluth, Janet Weaver, Emma Wong, Eve Holt, Charles Morris, Tracey Ramos순서대로 추천 검색어가 뜹니다.
제가보기엔 이 방식이 코드를 효율적으로 짜는데 도움이 될 것 같은데 여러분들의 의견 부탁드립니다.

**Comment by poeo1877** [comment]
위 방식은 추천 검색어가 가변적인 것인가요 아니면 어떤 값(ex. coal import) 이 고정으로 추천 검색어로 뜨는 것 인가요?

**Comment by kimnamhyeon0112** [comment]
추천검색어를 저희가 직접 선택해서 지정하는것이기 때문에 고정에 가까울 것 같습니다
가변은 찾아봐야 정확히 알 수 있겠지만 구현이 어렵지 않을까 하는 생각이 듭니다.
그러나 output으로 보여드릴 정보들이 정해져있기 때문에 가변성은 크게 문제가 될 것 같진 않다고 생각합니다.
저희가 output으로 보여드릴 정보들만 추천검색어로 뜨게끔 하면 되기 때문입니다.

**Comment by poeo1877** [comment]
좋은 방법인 것 같습니다. 저도 추천 검색어 기능 방법을 생각 중인데, code 작성하고 결과물을 보고 다시 논의하면 좋을 것 같습니다

**Comment by poeo1877** [comment]
추천 검색어 기능 구현하였습니다. 나중에 bash shell처럼 tag 키를 누르면 자동 완성 되는 기능이 있으면 멋지겠네요.
