### ISSUE TITLE
README.md가 삭제된 건에 대하여

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#11]
README.md가 삭제된 것 같던데 삭제하신 이유가 있으신가요?
의도치 않은 것이라면 제가 README.md파일 다시 만들까 합니다.

**Comment by poeo1877** [comment]
기존 README.md 파일은 과제 양식에 맞지 않았으니 새로 branch 따서 만드는 것이 좋을 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
과제 양식이라면 프로젝트 관리배점표 ppt의 코드부분 README.md부분(3page)이 조건에 부합하지 않는다는 뜻인가요?
이해가 잘 되지 않는데 설명해주실 수 있나요?

**Comment by poeo1877** [comment]
말씀하신 pdf 부분에서 설치 방법, 의존성, 사용 방법, 라이선스 및 연락처 부분이 README.md 에 적혀있지 않았으니 새로 그 형식에 맞게 새로 만드는 것이 좋을 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
네 알겠습니다
