### ISSUE TITLE
자료 조사 시 국가와 대륙 단위에 대한 궁금증

### ISSUE THREAD

**Issue by huntedu** [kimnamhyeon0112/Open_Source_Project#12]
저희의 프로젝트 목표가 1차로 국가 단위로 분석하고 더 나아가 2차로는 도시 단위까지 분석할 계획이라고 생각하고 있습니다. 그런데,
자료를 조사하다 보니 힘들 것 같다는 생각이 들었습니다. 도시 단위 자료를 구하기는 쉽지 않고, 국가 단위에서도 유럽 연합 같은 경제 통합체 같은 경우는 하나로 합쳐 통계를 낸 자료들이 많았습니다. 이제 각 원자재의 재고량, 소비량 부분이 남았는데 유럽 연합을 국가 단위로 쪼갠 자료를 찾기 힘들다고 느꼈습니다. 이러한 해결방안으로,

1.  유럽 연합과 같이 국가를 합친 자료 밖에 찾을 수 없다고 판단하여 그 부분은 No Data로 남긴다.  
2.  통합체나 대륙을 제외하고 나머지 국가들 순으로 출력한다.
3.  통합체 나라 정도는 사용한다.  

정도로 생각하고 있습니다. 여러분의 생각이 궁금해 이 안에서 논의하기 위해 이슈를 작성했습니다.

**Comment by huntedu** [comment]
국가 단위 자료는 못 찾았지만 EU를 포함한 데이터를 찾은 칸은 빈칸으로 최신화하였습니다. 
에너지와 광석은 매장량 (reserves) 데이터만 자료가 존재하고, 작물은 재고량 (stocks) 데이터만 자료가 존재하여 에너지와 광석의 재고량, 작물의 매장량을 채워 놓지 않았습니다. 수입량과 수출량은 최대한 자료에서 ton 단위로 찾아보고 만약 없으면 trademap.org라는 ITC 웹사이트에서 UN DATABASE를 사용하는 것을 확인하고 자료를 가져왔습니다.

**Comment by poeo1877** [comment]
우선 도시 단위 분석은 지도 구현에 어려움이 있어 제외하게 되었습니다. 따라서 도시 단위 자료는 필요 없습니다.

재고량 부분은 OECD 국가 중 상위 일부 국가의 재고량을 소개하는 것의 의의가 있으니 대륙 단위로 정보를 표기하는 방식은 올바르지 않다고 생각합니다. 하지만 소비량 부분은 대륙(유럽연합)으로 묶인 곳의 자료도 사용해도 크게 문제가 될 것 같지는 않습니다.

**Comment by kimnamhyeon0112** [comment]
말씀하신 방안 중 3번이 가장 나은 것 같습니다. 2번에 통합체는 유럽 연합을 말씀하시는 것 같고 대륙을 제외한다는 것은 무엇을 말씀하시는 건지 헷갈립니다. 1번은 자료의 양이 적어질 것이 염려되고요.

**Comment by huntedu** [comment]
그럼 소비량 부분은 유럽연합으로 묶인 곳의 자료를 사용하도록 하고, 재고량에 대해서는 좀 더 고민해보겠습니다.

**Comment by huntedu** [comment]
에너지와 광물은 매장량에 대한 자료만 존재하고, 농작물의 재고량은 EU를 포함한 자료만 존재하여 그대로 추가하였습니다. 다만, 기존의 재고량은 OECD 국가 중 일부 국가를 소개하는 것에 의의를 두었지만, 농작물의 재고량 같은 경우는 OECD 국가를 소개하는 것보다는 전체 국가의 재고량 순으로 자료를 추가하는 것이 좋다고 생각하여 자료를 추가하였습니다. 그리고, 철광석, 리튬, 코발트의 소비량은 자료를 찾지 못했습니다.
