### ISSUE TITLE
세계지도에 국가명 표기방법

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#15]
Feature_WorldMap branch에서 세계지도 부분에 마우스를 올리면 해당 국가 명이 나타나도록 구상하고 있습니다.
html에서 모든 <path> Tag에 title 속성을 입력해 구현하는 방식도 있겠지만, 이는 번거로울 것으로 생각되어 JavaScript에서 마우스를 올리면 해당 class명을 띄우는 방법을 생각했습니다. 하지만, 이 방식을 코드로 작성하는데 어려움이 있습니다. 
혹시, 제가 고안한 방식으로 코드를 작성하실 줄 아시거나 다른 방식으로 이 문제를 해결해 주실 분이 필요합니다.

**Comment by poeo1877** [comment]
@huntedu 조원 분 께서 책임지고 구현 부탁드립니다. 기한은 이번 주 일요일 저녁 전 까지고 JavaScript로 구현 안되면 html에서 title 속성으로 전부 부여하는 방법을 쓸 수 밖에 없습니다.

**Comment by huntedu** [comment]
Feature_Pointerevent 브랜치에 구현하였습니다.
