### ISSUE TITLE
Actions tab에서 git page 관리에 대해 궁금증

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#17]
분명히 예전에 main branch로 git page를 만들었는데, 지금 확인하니 Feature_WorldMap branch 내용을 토대로 git page를 만드는 것 같습니다. 따로 branch 설정을 바꾸지 않았다면 자동으로 된 상황인데, 만약 그렇다면 main branch의 존재가 희미해지는 것 같습니다.
main branch를 어떻게 관리하는 것이 좋을까요?

**Comment by poeo1877** [comment]
실제로 구현되는 branch는 지금 당장 main branch가 아닐지라도 main branch에는 그 시점에서 source code 상 문제 없는, 바로 실행 가능한 파일들 만 모아두는 역할만 하도록 하는 것이 나을까요?

**Comment by kimnamhyeon0112** [comment]
Feature_WorldMap branch를 main branch에 merge하는 방법은 없을까요?

**Comment by poeo1877** [comment]
아까 회의에서 github page는 안 쓰는 방향으로 가도록 정했으니 이 논의 필요성은 없어진 것 같습니다.
