### ISSUE TITLE
원자재 가격 값 얻는 방법

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#18]
원자재 가격을 어떤 API를 통해 구현할 지 알아보고 있습니다. 여러 API 중 무료로 적당히 쓸 수 있는 것을 추려보면
1. nasdaq api
2. IEX cloud api
3. marketstack api

추가로...
google sheet finance로도 값을 얻을 수 있을 것 같으니 한 번 알아보겠습니다. 

더 좋은 api가 있다면 글 남겨주세요

**Comment by poeo1877** [comment]
commodities-api : 한 달에 100번 api 요청만 가능해서 프로젝트에 적합하지 않습니다.

**Comment by poeo1877** [comment]
Nasdaq api를 기준으로 code 작성 중 입니다. 더 좋은 API가 있다면 댓글 부탁드립니다.

**Comment by poeo1877** [comment]
Energy 부분은 eia api 사용 할 예정입니다. Nasdaq api 보다 더 많은 data를 무료로 제공하기에 채택하였습니다.

**Comment by kimnamhyeon0112** [comment]
api.commoprices.com이라는 사이트를 찾았는데 프로젝트에 포함시킨 원자재의 정보가 대부분 포함되어있어 추가했습니다.
정보 업데이트 주기는 자주 있는 것 같은데 json여부와 더불어 더 알아보겠습니다.
cobalt, lithium, corn, oats도 있긴하나 이 4가지 항목에 대해선 구독이 필요합니다. 따라서 이것도 따로 찾아보겠습니다.

**Comment by kimnamhyeon0112** [comment]
gold, silver api받아오는 사이트 유료네요. 죄송합니다

**Comment by kimnamhyeon0112** [comment]
Lithium, Gold, Silver, Copper, Nickel, Aluminium, Zinc, Tin, Cobalt, Lead, Iron Ore에 대한 api를 받아올 수 있는 사이트
https://www.metals-api.com/를 찾았습니다. 구독형태긴 한데 무료도 있고 json형식으로 받아옵니다
조금더 찾아보겠습니다.

**Comment by huntedu** [comment]
https://fred.stlouisfed.org/ 에서 Argiculture commodity 관련한 Price data를 api로 받아올 수 있는 사이트를 발견하여 이 api를 이용하였습니다.
