### ISSUE TITLE
다른브랜치에 체크아웃이 되지 않습니다 도움 부탁드립니다.

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#19]
환태님께서 올리신 csv파일 확인 차 Feature_PieData 브랜치에 체크아웃하여 csv 파일들을 열람후 해당 파일들을 닫아놓은 상태입니다.
그후 다시 Feature_CircleChart에 체크아웃 한 상태인데, 이대로라면 제 로컬에 연결한 리모트 repo에 DB폴더가 없어져야 하는데 DB폴더가 그대로 남아있고 git graph상에서 uncommited change라는 안내문구가 뜨며 csv파일들이 열려있다고 작성되어있는 것 같은데 DB폴더 지워도 될까요? 이것 때문에 다른 브랜치에 체크아웃이 안되는 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
git status로 확인해보니 Feature_CircleChart에 DB폴더가 들어있다고 나옵니다.
이미 Feature_PieData에 DB폴더가 있으니 Feature_CircleChart에서 DB폴더를 지울까요?

**Comment by poeo1877** [comment]
csv 파일을 열고 안 닫은 상태로 git checkout을 하셨나요? 아니면 csv 파일을 수정한 뒤 checkout 한 것이면 수정 사항을 저장 하지 않고 checkout을 해서 그런 것일 수 도 있습니다. 한 번 확인해 보시고 정 안된다면 무식하지만, 전부 지우고 다시 git clone 받으시는 것도 방법이긴 합니다.

**Comment by kimnamhyeon0112** [comment]
따로 파일을 수정하진 않았으므로 닫지않고 checkout한듯 싶습니다. 일단 Feature_CircleChart에서 DB폴더를 지우는 방향으로 해결하겠습니다.

**Comment by kimnamhyeon0112** [comment]
로컬에서 DB폴더를 지워 해결했습니다. 조언감사드립니다.
