### ISSUE TITLE
Web page mockup

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#2]
### 목적
 이번 프로젝트에서 만들 웹페이지가 사진에 어떻게 있을지, 어떻게 단어를 배치할 것인지 등 모두 공통의 이미지를 정하기

### 방식
해당 목적만 달성한다면 그 방식은 상관없습니다. A4에 연필로 그려도 되고 그림판에 그려도 되고, mockup web page를 도와주는 tool을 써도 됩니다. 우선 모두 프로젝트 가명, commodity world map 이 어떻게 생겼을지 이미지를 commit해 주세요. 

_commit message type은 docs라 분류해도 될 것 같습니다_

**Comment by poeo1877** [comment]
[Project Mockup.zip](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8403521/Project.Mockup.zip)
간단하게 만들었는데 어떻게 생각하시나요?

**Comment by kimnamhyeon0112** [comment]
생산물량이 지자체별로 다르므로 국가단위로 보여주는것도 좋지만 지자체별로 쪼개서 더 세밀하게 보여주는 것도 좋을 것 같습니다. 전 세계를 다루다보니 자세하게 찾는 것이 힘들기 때문에 미국이나 호주의 경우 주 단위, 우리나라의 경우 특별시, 광역시, 도 단위로 쪼개서 보여주는 정도는 괜찮을거 같습니다. 관련 목업은 찾으면 올려드리고 못찾으면 그려서 올려드리겠습니다.

**Comment by kimnamhyeon0112** [comment]
가장 비슷한 예시를 찾았습니다. 참고바랍니다.
[Mockup 보완.docx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8403786/Mockup.docx)

**Comment by poeo1877** [comment]
국가 단위에서 더 작은 단위로 나눠 보여줬을 때 예상하신 좋은 점이 있나요?
개인적으로 한국만 따로 빼서 상세하게 보여주는 부가 기능이라면 국가 간  원자재 무역 사이에 한국의 현 위치를 쉽게 알 수 있을 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
딱히 큰 의미를 두진 않았습니다만 말씀하신 것도 적용할 수 있고요.
특정 지역에서 많이 생산한다면 그 지역의 특산품으로 볼 수 있겠죠. 제주 감귤, 횡성 한우등이  그 예시일 것입니다.
궁금한 사람도 있고 아닌사람도 있겠지만, 저의 경우엔 수입품목이 어느 나라의 어느 지역에서 나온 것인지 알려준다면
이런 특산품에 빗대어 볼 때, 더 품질 좋은 품목을 수입하는 데 도움을 줄 수 있을거 같다고 생각합니다.
반대로 수출도 마찬가지 이구요.

**Comment by kimnamhyeon0112** [comment]
목업본 올려드립니다 확인 부탁드립니다
[김남현 목업본.pptx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8417326/default.pptx)
※ 각 장별 설명
1장: 메인화면
2장: 검색
3장: 검색후 화면
4장: 원그래프 단추 클릭시 좌측에 정보 print, 단추를 다시 누르면 정보창 닫히게 만들 예정
5장: 막대그래프 단추 클릭시 좌측에 정보 print, 위와 내용 같음

**Comment by poeo1877** [comment]
검색 후 재검색을 원하는 경우에는 어떤 방식으로 서비스를 제공하실 생각이신가요?
      ex) 석유 검색 후 천연가스를 검색하려고 하는 상황

**Comment by kimnamhyeon0112** [comment]
홈버튼 혹은 링크를 추가하면 간단히 해결됩니다.
