### ISSUE TITLE
막대그래프 구현에 관한 질문

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#20]
막대그래프 구현을 위해 코드를 짜려는 도중 구현방향에 대해 여러분의 의견이 궁금하여 의견을 묻고자 이슈글 남깁니다.
CircleChart의 코드를 보시면 아시다시피 원형그래프는 한가지의 원자재에 대한 import, export등을 한번에 표기하기 어렵습니다.
그래서 국가별 import, export등을 따로따로 표기할 수 있게 코드를 짜야합니다.
다만 막대그래프는 아래 올려드리는 파일에 나오는 것처럼 한번에 한가지 원자재에 대한 import, export등을 한눈에 보이게끔 하려 합니다. 이에 대한 여러분의 생각은 어떠하신지 아래 파일을 확인하시고 의견남겨주시면 감사하겠습니다
[막대그래프 예시.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8708527/default.xlsx)
.

**Comment by kimnamhyeon0112** [comment]
원형그래프 때문에라도 수입국, 수출국, 재고량, 생산국, 소비국, 매장량 버튼을 살려야 하는 것은 맞기때문에 원형차트처럼 하나씩 분리해도 상관은 없습니다만 모든 자료를 한눈에 보는 것도 괜찮을 것 같다 생각합니다

**Comment by poeo1877** [comment]
따로 따로 코드를 짤 이유가 없습니다. chart data는 검색한 내용만 보여주기만 하면 됩니다. 예를 들어 coal import 상황이면 import에 해당하는 국가들만 막대 그래프로 보여주면 됩니다. 원 그래프도 동일한 맥락입니다.
만약 모든 자료를 한 눈에 보는 것을 원한다면 그것은 따로 버튼을 추가하거나 원자재 명만 입력 (ex. coal) 한 경우에만 보여주면 됩니다. 이는 차후에 논의하면 될 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
알겠습니다.

**Comment by poeo1877** [comment]
막대 그래프 보다는 도넛 차트가 더 직관적으로 이해할 수 있을 것 같아서 도넛만 하겠습니다.
