### ISSUE TITLE
원자재 표기 기간에 대한 논의

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#22]
원자재 가격 부분에서 해당 기간을 얼만큼 잡고 보여줄 지 고민입니다. 
우선 임의로 6개월로 설정을 하였으나 실제 사용자에게 도움이 될 적정한 기간은 어느 정도가 좋을 지 논의가 필요합니다.
다른 조원 분들은 어떻게 생각하시나요?

**Comment by kimnamhyeon0112** [comment]
전 1년이 좋을 것 같다고 생각합니다.

**Comment by poeo1877** [comment]
되도록 2021-01-01로 시작일을 잡겠습니다.
