### ISSUE TITLE
Feature_Pointerevent 구현 버그

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#25]
처음 web page가 생성된 후 첫 클릭을 국가가 아닌 다른 곳에 클릭을 하면 "Tooltip text" 가 생성되는데 코드를 보면 의도한 것과 다르게 뜨는 것 같아 수정이 필요해 보입니다.
![image](https://user-images.githubusercontent.com/67182280/170966736-81e3ca5a-314c-4237-aaf1-bb1856af0af1.png)

**Comment by huntedu** [comment]
버그 수정했습니다.
