### ISSUE TITLE
DB 구축을 위한 준비

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#26]
DB는 mysql를 사용하기로 전에 이야기를 했는데 이를 자신의 컴퓨터에 설치하고 그와 관련된 다른 프로그램들 (apache, php, phpmyadmin)을 설치해야 합니다. 하지만 이것들을 따로 설치해  path를 설정하기엔 그 과정이 복잡합니다. (직접 해봄)
따라서 Bitnami WAMP를 통해 DB 구축을 위한 준비를 하는 것이 좋을 것 같습니다. 저처럼 따로 설치해 번거로운 과정을 안 겪기를 바랍니다.

**Comment by huntedu** [comment]
다행히도 bitnami wamp를 사용해 설치 후 진행 중 이었습니다. 다만, bitnami wamp를 사용하니 mariaDB가 설치됐습니다. 찾아보니 mysql의 신버전(?) 인 것 같습니다. mysql의 모든 명령어가 동일하지만, 동시에 사용하면 오류가 발생할 수도 있다고 합니다. 저는 mariaDB를 사용하고 있습니다.
