### ISSUE TITLE
원자재 자료 조사

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#3]
제공할 서비스를 위해 필요한 자료를 어디서 참고할 지 정할 필요가 있습니다. 
자료의 신뢰성이 프로젝트 목적에 중요한 요소이기에 해당 자료의 출처 및 신뢰도는 매우 중요합니다. 따라서 출처 꼭 표기해주세요.
자료는 잘 정리해서 기획  폴더에 넣어 commit 해 주세요. 

_교내 도서관에 참고할 만한 자료를 알아보았으나 없었기에 인터넷에서 찾는 것이 좋을 것 같습니다._

**Comment by huntedu** [comment]
2021년까지 자료들을 품목 별로 액셀 파일 형식으로 다운 받을 수 있는 웹사이트 몇 가지 정도를 추려봤습니다.  신용 할 만한 웹사이트라고 생각됩니다.
