### ISSUE TITLE
중간 발표에 대한 논의

### ISSUE THREAD

**Issue by poeo1877** [kimnamhyeon0112/Open_Source_Project#4]
발표를 어떤 방식으로 어떻게 할 지 각자 생각하신 점을 공유하는 것이 좋을 것 같습니다.

발표 기준에서...
필요성, problem, solution이 중요한 요소이니 이를 고려해서 어떻게 발표를 하면 좋을지 글을 남겨주세요.

**Comment by poeo1877** [comment]
제 생각에...
필요성 부분에서 원자재 가격과 금융 시장, 실질적으로 쉽게 느껴지는 소비자 물가, 금리의 최근 추이와 관계를 설명하고 이 문제가 중요하다는 점을 근 2년간 개인 투자자 및 증권 계좌 증가 수치를 근거로 이야기를 시작해 우리의 프로젝트가 의미 있다는 것을 언급하는 것이 좋을 것 같습니다.
problem에서는 앞서 언급한 관계에 대해 직관적이고 정확한 정보를 얻을 수 있는 기능을 input -> process -> output 순으로 간단하게 언급하고 solution 단계에서 기능에 대해 상세하게 설명하면 좋을 것 같습니다. 

저희가 제공할 서비스를 미리 제공하던 web site를 조사하여 차별성에 비교 자료로 쓰는 것이 좋을 것 같습니다.

전체적인 비중으로 필요성 부분이 가장 큰 비중을 차지할 것 같고 이를 잘 설명해야 조금 더 마음에 와닿는 프로젝트가 될 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
저의 경우에 필요성은 펜데믹사태로 인한 투자 붐이 일어난 것을 계기로 일반인의 투자증권 계좌 개설 수치를 설명하고 그에따라 어떤 변화가 있었는지. 상관관계를 설명해 우리의 프로젝트가 현재 전세계적인 이슈를 다룬다는 것에 중점을 두려고 합니다.
이때, 코로나19시작~현재까지 투자판을 간략히 설명하고 우리의 프로젝트를 대입시키면 도움이 될거라 생각합니다.
problem은 제가 만든 Mock-up을 발표자료로 참고하여 input에 따른 output이 어떻게 이루어 지는지, 이 Mock-up에서 solution을 같이 다뤄 기능적인 부분을 설명하고자 하려 합니다. 차별성 부분은 필요성 부분에서 언급한 예시와 우크라이나 전쟁을 예시로 들어 이러한 이슈가 현재 전세계적으로 미치는 영향을 설명하고 그에 따른 우리 webpage의 강점을 설명하여 차별성을 제시하고자 합니다.

**Comment by kimnamhyeon0112** [comment]
그리고 발표자료를 만들면서 한가지 의문점이 생겼는데 제가 대본을 만들며 B2B와 B2C의 충돌이 생기는 것 같던데 정확한 가닥을 어디로 두는것이 좋을까요?
B2C의 경우 일반인의 주식투자를 예시로 들 수 있고 B2B의 경우 우크라이나 전쟁으로 인한 유가상승을 통해 대체수급처를 찾는 국내 수입처와 해외시장의 관계를 예시로 들겠습니다.

**Comment by huntedu** [comment]
필요성은 말씀하신 것들에 추가로 덧붙이자면 교육용으로 생각하는 것도 좋을 것 같습니다. 각 국가별 생산량이나 이동량들을 확인하여 해당 정보에 따라 전체적인 흐름을 읽는데 도움이 될 것 같고, 경제 개념을 공부하는 데 필요한 추가 자료들로 사용할 수 있을 것 같습니다. 
Problem에서는 원하는 국가와 정보의 종류(ex. 수출량)가 input되면, output으로  정렬된 정보가 웹사이트 창에 직관성이 좋은 방법으로 표시되게 설계하는 방향으로 생각하고 있습니다.
차별성에서는 조사한 원자재 관련 사이트 1~2개의 특징과 저희 프로젝트의 특징을 비교하여 보여주는 방향으로 생각하고 있습니다. 떠오르는 건 ' 제공되는 정보의 종류가 많다.' 정도입니다.

그리고 추가로 저희가 만드는 프로젝트의 이름을 따로 정해서 발표할 때 쓰는 것도 좋을 것 같습니다.
아직 생각한 것은 없지만 원자재 사이트보다는 ITC나 WIT처럼 네이밍을 하는 게 어떨까요?

**Comment by kimnamhyeon0112** [comment]
좋은 지적 감사드립니다.
problem관련해서는 제가 만든 issue에 각자 ppt를 커밋함으로써 서로 비교해보고 그에대한 토의를 해보는것도 좋을 것 같다 생각듭니다. 다만 말씀해주신 것과 제가 구상한 ppt를 비교해볼 때 저와 비슷한 방향이라 생각됩니다. 차별성 관련해서는 저도 관련 웹사이트를 찾아서 비교해봐야 할 것 같습니다.
프로젝트 네이밍은 따로 이슈를 만들어 토의해보는 것이 좋을것 같습니다.
