### ISSUE TITLE
중간 발표에 대한 ppt

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#6]
중간 발표에 대한 ppt를 각자 만드셨으리라 생각됩니다.
각자 만든 ppt를 비교해보고 발표시 사용할 ppt를 선정하고자 하니 각자 만드신 ppt를 커밋해주시기 바랍니다.
또한 발표를 어떻게 진행할 것인지 대본을 만드신 것이 있다면 추가해 주시거나 아니면 간략한 설명도 덧붙여주시기 바랍니다.

**Comment by poeo1877** [comment]
main branch에 commit 하기 보다는 이 이슈글에서 ppt파일을 올리고 논의하는 것은 어떤가요? ppt에 대한 설명도 여기서 댓글로 달면 한 번에 볼 수 있고 좋을 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
말씀해주신 방법이 더 나은거 같습니다. 저도 comment로 올리겠습니다.

**Comment by huntedu** [comment]
ppt를 만드실 때 필요한 참고자료를 올리겠습니다.

필요성 부분
개인 투자자 거래 대금을 연도별로 표시한 그래프와, 국제 유가와 세계 경제 성장률 그래프를 하나씩 만들어 두 개의 그래프를 비교하는 용도로 올렸습니다.

1.  개인 투자자 거래 대금
![개인 투자자 거래 대금](https://user-images.githubusercontent.com/88420060/163796833-ba0aa7f7-6a39-47b6-908a-4d9eecbbe9b0.jpg)

2. 국제 유가와 세계 경제 성장률 비교 그래프
[국제 유가와 세계 경제 성장률 비교.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8505124/default.xlsx)
출처 : 1) 국제 유가 https://www.istans.or.kr/su/newSuTab.do?scode=S121 
          2) GDP https://www.imf.org/external/datamapper/NGDP_RPCH@WEO/OEMDC/ADVEC/WEOWORLD 

차별성 부분
저희가 하는 프로젝트 관련 웹사이트를 조사해봤습니다.

1. [wits.worldbank.org](https://wits.worldbank.org/CountryProfile/en/Country/WLD/Year/LTST/TradeFlow/Export/Partner/by-country/Product/Total) 
  - World, Product, Year, TradeFlow를 입력하면, 국가를 크기 순으로 분할한 그림과 Table View가 나온다.
2. https://www.trademap.org/
  - Hs code로 분류된 자료의 종류, TradeFlow를 입력하면, 상위에 있는 국가들을 그래프로 표시하고, 지도에 양에 따라 색을 표시한다.
4. [ipad.fas.usda.gov](https://ipad.fas.usda.gov/ogamaps/Default.aspx)
  - 농작물 관련 품목들의 생산량, 수입량, 수출량을 표시한다. 지도에 양에 따라 색을 다르게 표시한다. Input은 따로 존재하지 않는다.

**Comment by huntedu** [comment]
필요성 부분 참고자료 수정 내용입니다.
1. 개인 투자자 거래 대금
![개인 투자자 거래대금](https://user-images.githubusercontent.com/88420060/163805228-77d7c4b4-d95d-46b1-b4d9-23a7caecdef6.jpg)


2. 국제 유가와 세계 경제 성장률 비교 그래프
[국제 유가와 세계 경제 성장률 비교.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8505494/default.xlsx)

**Comment by kimnamhyeon0112** [comment]
작성한 ppt와 대본입니다.
[김남현 중간발표 대본.txt](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8505778/default.txt)
[전세계 원자재.pptx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8505779/default.pptx)

**Comment by huntedu** [comment]
원자재 지수와 주요 국가 지수 비교 파일입니다.
[원자재 지수와 주요 국가 지수 비교.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8512009/default.xlsx)
DJ와 S&P GSCI 원자재 지수와 코스피, 나스닥, S&P 500 지수를 비교하였습니다.
다른 원자재 지수인 bloomberg commodity 지수와 CRB 지수는 값이 크지 않아 비교하였을 때 눈에 띄게 보이지 않아 제외했고, RICI 지수는 2020년 5월부터 19년 5월까지의 자료를 찾지 못하여 추가하지 않았습니다.
주요 국가 지수에 다른 어떤 지수를 넣으면 좋을지 의견 부탁드립니다.

**Comment by poeo1877** [comment]
한국, 미국이랑 원자재 지수 2개 정도 같이  하나의 차트에서 비교하면 좋을 것 같습니다. y축의 실제 값 보다는 모든 지수들의 방향성이 연관이 있다는 사실을 나타내는 정도면 충분할 것 같습니다

**Comment by huntedu** [comment]
지금의 그래프는 방향성이 한눈에 봤을 때 와닿지 않다는 말씀이신가요? 다우존스 지수 이외에는 연관이 있어 보이는데 다우존스 지수를 빼고 다른 원자재 지수를 추가하는 편이 좋을까요?

**Comment by poeo1877** [comment]
그것도 좋은 방법이 될 수 있을 것 같습니다. 다만 각 그래프의 거리(이격도)가 심해서 한 눈에 모든 그래프가 연관성을 지닌다 알아보긴 어려울 것 같습니다. 또한 그 기간이 짧아 아쉽습니다. 기간이 길어도 모든 지수가 유사한 방향성을 갖는다는 사실을 보여주면 지수 간 상관관계가 있다는 주장의 좋은 근거가 될 것입니다

**Comment by poeo1877** [comment]
CRB 지수를 추가하는 것도 좋아보입니다

**Comment by kimnamhyeon0112** [comment]
혹시 주식 개인투자자 증가 지표에 대한 조사자료가 있나요?
repo에 커밋된 자료들을 살펴보았는데 따로 없는 것 같아서 자료가 없으면 추가 조사하고자 합니다.

**Comment by huntedu** [comment]
CRB 지수를 추가하고 값이 낮은 지수에 대해서는 보조축으로 작성해 모든 그래프가 연관성 있게 만들어 보았습니다.
[원자재 지수와 주요 국가 지수 비교.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8512833/default.xlsx)

다만, 가로축을 항목을 거꾸로 하게 되면 보조축은 항목 거꾸로가 적용이 되지 않습니다. 그래서 2022년부터 시작돼 항목이 거꾸로 보입니다. 해결할 방법을 아시는 분 있나요?

**Comment by poeo1877** [comment]
[OSS 중간발표_김유신조.pptx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8512884/OSS._.pptx)
[발표 script.docx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8512885/script.docx)
작성한 대본 및 ppt입니다. 개인 투자자 증가 지표에 대한 것은 지금 업로드 된 ppt에 있는 내용 외에는 없습니다.

**Comment by huntedu** [comment]
[원자재 지수와 주요 국가 지수 비교.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8513003/default.xlsx)

**Comment by kimnamhyeon0112** [comment]
[주식투자 활동계좌 수 증가 추이 및 주식시장 관심도.docx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8513087/default.docx)
주식투자 활동계좌 증가 추이는 이미 ppt에 자료가 있기때문에 주식시장 관심도를 추가자료로 사용하면 도움이 될듯 싶습니다.

**Comment by kimnamhyeon0112** [comment]
[연도별 물가상승률(국내).xls](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8513244/default.xls)
[연도별 물가상승률(해외).xls](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8513245/default.xls)
연도별 국내와 해외의 물가상승률 자료입니다. 국가지표체계 출처입니다.

**Comment by huntedu** [comment]
[원자재 지수와 주요 국가 지수 비교.xlsx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8513834/default.xlsx)
년도 수정하였습니다.

**Comment by kimnamhyeon0112** [comment]
[국내 기후문제에 따른 농산물 물가변동.docx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8514425/default.docx)
2020년 9월 잇다른 태풍과 장마 폭염등 자연재해에 따른 19년 9월대비 농산물 가격변동표 자료입니다.

**Comment by kimnamhyeon0112** [comment]
[여러원자재들의 가격추이.docx](https://github.com/kimnamhyeon0112/Open_Source_Project/files/8514623/default.docx)
여러 원자재들의 가격추이를 살펴 대부분의 원자재의 가격상승을 확인할 수 있는 자료입니다.
