### ISSUE TITLE
프로젝트 네이밍에 관한 discussion

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#7]
우리가 프로젝트 네이밍에 관해 토의한 것이 없기때문에 여러분이 올려주신 ppt 자료의 프로젝트 네이밍이 서로 다를거라 생각합니다.
따라서 이번 이슈에서는 네이밍에 관한 토의를 진행하여 우리의 프로젝트의 네이밍을 정할 필요가 있다고 생각합니다.
좋은 의견이 있으시다면 간단한 이유도 함께 올려주시기 바랍니다.

**Comment by kimnamhyeon0112** [comment]
각자 올려주시면 토의를 통해 결과를 선출하거나 투표를 진행할까 합니다.
자유롭게 의견 작성해주시면 감사하겠습니다.

**Comment by kimnamhyeon0112** [comment]
저의 경우 전세계 원자재 찾기라는 이름을 생각해두었습니다. 다만 해당 네이밍은 사용자가 한국어를 쓰는 사람에 한정되어 있다는  허점이 존재하기 때문에 영어로 네이밍을 작성하는 것이 더 좋을 것 같다는 지적을 받아들여 영문 네임을 제시하겠습니다.
따라서 World's Raw Materials in one Page라는 네이밍을 제시합니다. 그리고 긴 네이밍을 약자로 딴 Wrap을 메인 네임으로 사용하려고 합니다. wrap이라는 단어가 포장하다라는 뜻을 가졌다는 것을 생각해보면 저희 프로젝트와 어느정도 연관성도 있다고 생각하고 사람들에게 각인되기 쉬울것 같다고 생각합니다.

**Comment by poeo1877** [comment]
프로젝트에서 말하는 원자재가 raw materials 보다는 commodity에 더 가까운 것 같습니다. 또한 제공하는 서비스의 형태가 원자재의 어떠한 위치에 대한 정보이므로 프로젝트 명을 보고 연관 지을 수 있으면 좋을 것 같습니다.
따라서 World Commodities Location Map 이라는 프로젝트 명이 좋을 것 같습니다.

**Comment by kimnamhyeon0112** [comment]
commodity가 더 옳은 표현이군요.
그렇다면 이름은 사람들에게 쉽게 각인될만한 이름이 좋다고 생각하는데, 제시하신 이름도 괜찮지만 저처럼 줄였을 때 한 눈에 알아보기 쉬운 다른 제목도 제시해 주실 수 있나요?

**Comment by poeo1877** [comment]
개인적으로 굳이 줄임말을 써야 하는가? 라는 생각이 있습니다. 많은 사람에게 알려지기 전 줄임말로 처음 소개된다면 그 말로 한 번에 서비스를 유추하기 어려울 것 같습니다. 따라서 줄임말은 쓰지 않으며 최소한의 단어로 소개하는 것이 좋을 것 같습니다
