### ISSUE TITLE
중간 발표에 관한 test용 html파일

### ISSUE THREAD

**Issue by kimnamhyeon0112** [kimnamhyeon0112/Open_Source_Project#9]
저와 poeo1877님께서 서로 중간 발표때 사용할 test용 html파일을 pull request하여 둘을 비교하고자 합니다.
확인부탁드립니다.

**Comment by poeo1877** [comment]
저는 중간 발표에 쓸 html 파일은 Feature_WorldMap을 활용할 생각입니다. 
main branch에 갈 파일들이니 둘 중에서 gitpage에 올라갈 index.html 파일을 정하면 될 것 같습니다

**Comment by kimnamhyeon0112** [comment]
Feature_WorldMap의 소스코드를 봤는데 이미 세계지도 소스를 구현해놓으셨군요.
main branch에서 사용할 지도 소스가 필요하니 Feature_WorldMap을 사용하면 될듯 싶습니다.
